"use client";

import { Header } from "@/components/chrome/Header";
import { Footer } from "@/components/chrome/Footer";
import { LegalShell } from "@/components/modules/LegalShell";
import { useT } from "@/i18n/I18nProvider";

const cookies = [
  {
    name: "consent",
    category: "Strictly necessary",
    purpose: "Stores your consent choices.",
    duration: "12 months",
  },
  {
    name: "vg-locale",
    category: "Strictly necessary",
    purpose: "Stores your selected interface language.",
    duration: "12 months",
  },
  {
    name: "session",
    category: "Strictly necessary",
    purpose: "Maintains form state across the multi-step application flow.",
    duration: "Session",
  },
  {
    name: "analytics",
    category: "Analytics",
    purpose: "Privacy-friendly aggregate analytics. No personal identifiers stored.",
    duration: "30 days",
  },
];

export default function CookiesPage() {
  const t = useT();
  return (
    <>
      <Header variant="solid" />
      <main>
        <LegalShell
          eyebrow={t.pages.legalSidebar}
          title={t.footer.legalCookies}
          lastUpdated="May 2026"
          active="/legal/cookies"
        >
          <p>
            This site uses a small number of cookies. Strictly necessary cookies are set by default;
            analytics cookies are set only after explicit consent.
          </p>

          <h2 className="font-serif text-2xl text-navy mt-6">Cookie table</h2>
          <div className="overflow-x-auto">
            <table className="w-full mt-4 border hairline text-body-sm">
              <thead className="bg-cream-2 text-eyebrow uppercase text-slate-2">
                <tr>
                  <th className="text-left p-3 border-b hairline">Name</th>
                  <th className="text-left p-3 border-b hairline">Category</th>
                  <th className="text-left p-3 border-b hairline">Purpose</th>
                  <th className="text-left p-3 border-b hairline">Duration</th>
                </tr>
              </thead>
              <tbody>
                {cookies.map((c) => (
                  <tr key={c.name} className="border-b hairline last:border-b-0">
                    <td className="p-3 font-mono text-[0.85rem] text-navy">{c.name}</td>
                    <td className="p-3 text-slate">{c.category}</td>
                    <td className="p-3 text-slate">{c.purpose}</td>
                    <td className="p-3 text-slate-2 tabular">{c.duration}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <h2 className="font-serif text-2xl text-navy mt-6">Managing consent</h2>
          <p>
            You can change your consent choices at any time using the cookie preferences link in the
            footer. Withdrawing consent will not affect any browsing you have already completed under a
            previous consent state.
          </p>

          <p className="text-slate-2 text-body-sm mt-8">
            Note: this is placeholder text for the redesign stage. The final cookie table will be
            generated by the consent platform once it is wired up — and translated for each locale at
            that time.
          </p>
        </LegalShell>
      </main>
      <Footer />
    </>
  );
}
